version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: face_recognition
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
      - uploads_data:/app/uploads  # Persist uploads folder
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  uploads_data:  # Define the named volume for uploads
